using Titanium.Web.Proxy.Http;
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

public static class ProxyUtils {

    public static string BuildApiErrorMessage(Request r) => $"Some error was generated by the proxy. {(ProxyUtils.IsGraphRequest(r) ? (ProxyUtils.IsSdkRequest(r) ? "" : BuildUseSdkMessage(r)) : "")}";

    public static string BuildUseSdkMessage(Request r) => $"To handle API errors more easily, use the Graph SDK. More info at {GetMoveToSdkUrl(r)}";

    public static string GetMoveToSdkUrl(Request request) {
        // TODO: return language-specific guidance links based on the language detected from the User-Agent
        return "https://aka.ms/move-to-graph-js-sdk";
    }

    public static bool IsGraphRequest(Request request) => request.RequestUri.Host.Contains("graph", StringComparison.OrdinalIgnoreCase);

    public static bool IsSdkRequest(Request request) => request.Headers.HeaderExists("SdkVersion");
}